feature/SESC-7369_update_coding_challenge
gls-ecl/parcelshop pull request #2
Opened 2023-09-26 15:23 UTC by jean-pauledoh

Issue: https://gls-ce.atlassian.net/browse/SESC-7369

2023-10-05 07:54 UTC, kimakunc requested changes

2023-10-05 07:54 UTC, kimakunc commented on build.gradle.kts
> +    kotlin("plugin.lombok") version "1.9.10"
not need IMO

2023-10-05 07:54 UTC, kimakunc commented on src/main/kotlin/com/gls/parcelshop/model/Address.kt
> +import lombok.AllArgsConstructor
Hier ist noch lombok :)

2023-10-10 10:17 UTC, valoricDe commented on build.gradle.kts
> +    java
is this still needed?

2023-10-10 10:18 UTC, valoricDe commented on build.gradle.kts
> +    java
We also have kotlin("plugin.spring") version kotlinVersion no idea if this is necessary xD

2023-10-10 10:21 UTC, valoricDe approved these changes

2023-10-11 07:59 UTC, valoricDe approved these changes

2023-10-12 08:24 UTC, jean-pauledoh commented
Closing this PR. The merged kotlin version is available here: https://github.com/bettermile/parcelshopK

2023-10-12 08:24 UTC, closed without merging